### ISSUE TITLE
Need ability for a table result to have a sub-table

### ISSUE THREAD

**Issue by jeremyf** [nboughton/rollt#1]
There are cases in which we have a table has a result that says "roll 2 times on this table" (see Beasts p201 in the Free Version of SWN). Another common case is "roll on sub-table C"

Here is an implementation in Ruby: https://gist.github.com/jeremyf/715fb116d2874e1b7218df789bf3099f#file-random-table-rb-L6

**Comment by nboughton** [comment]
I've been meaning to look at this for a while but I have a teething 7 month old at the moment so haven't had the time. I'll have a look at the implementation tomorrow on my lunch break and see what can be done :)

**Comment by jeremyf** [comment]
@nboughton No worries, I'm prepared to spend a bit of time working on it. But there is quite a bit that I'm trying to understand.

**Comment by jeremyf** [comment]
I started working on a new Rubygem called "rollio" that encodes some of what I'm thinking. github.com/jeremyf/rollio

**Comment by nboughton** [comment]
Now that I've got the dynamic hex map stuff working I'll have another look at this. I had some ideas for a rewrite of the rollt lib that might accomplish it but I'll need to experiment.

**Comment by nboughton** [comment]
Table results can now call custom actions. I've also included a registry so that item.Action can call it's parent in a roundabout way. Now you can add an anonymous action to table.Item as per the example code in rollt.go:

    var r = rollt.NewRegistry()

    var t = rollt.Table{
	    Name: "Test",
	    ID:   "Parent",
	    Dice: "1d6",
	    Reroll: rollt.Reroll{
		    Match: []int{5, 6},
		    Dice:  "1d4",
	    },
	    Items: []rollt.Item{
		    {Match: []int{1}, Text: "Item 1", Action: func() string {
			    tbl, _ := r.Get("Parent")
			    return tbl.Roll()
		    }},
		    {Match: []int{2}, Text: "Item 2"},
		    {Match: []int{3}, Text: "Item 3"},
		    {Match: []int{4}, Text: "Item 4"},
		    {Match: []int{5}, Text: "Item 5"},
		    {Match: []int{6}, Text: "Item 6"},
	    },
    }

    var t1 = rollt.Table{
	    Name: "Subtable 1",
	    ID:   "Child 1",
	    Dice: "1d6",
	    Items: []rollt.Item{
		    {Match: []int{1}, Text: "Item 1.1"},
		    {Match: []int{2}, Text: "Item 2.1"},
		    {Match: []int{3}, Text: "Item 3.1"},
		    {Match: []int{4}, Text: "Item 4.1"},
		    {Match: []int{5}, Text: "Item 5.1"},
		    {Match: []int{6}, Text: "Item 6.1"},
	    },
    }

    func main() {
	    r.Add(t)
	    r.Add(t1)

	    //	fmt.Printf("%+v\n", t.Items)
	    for i := 0; i < 10; i++ {
		    fmt.Println(t.Roll())
    	}
    }

**Comment by nboughton** [comment]
The changes are also additive so no existing code built on rollt should break.
